POST http://localhost:3333/subscriptions
Content-Type: application/json

{
    "name": "maria estela",
    "email": "maria@email.com",
    "phone": "16666666666",
    "referrer": "c8c58869-f9aa-40c8-b907-df8ba9f11416"
}

###

GET http://localhost:3333/invite/c8c58869-f9aa-40c8-b907-df8ba9f11416

###
GET http://localhost:3333/subscribers/c8c58869-f9aa-40c8-b907-df8ba9f11416/ranking/clicks

###

GET http://localhost:3333/subscribers/c8c58869-f9aa-40c8-b907-df8ba9f11416/ranking/count

###

GET http://localhost:3333/ranking

###
GET http://localhost:3333/subscribers