POST http://localhost:3333/subscriptions
Content-Type: application/json

{
    "name": "soffia2",
    "email": "soffia2@email.com",
    "referrer": "46a47061-4e87-4e5f-aaba-f73699d53808"
}

###

GET http://localhost:3333/invite/46a47061-4e87-4e5f-aaba-f73699d53808

###
GET http://localhost:3333/subscribers/46a47061-4e87-4e5f-aaba-f73699d53808/ranking/clicks

###

GET http://localhost:3333/subscribers/46a47061-4e87-4e5f-aaba-f73699d53808/ranking/count